In [1]:
%config IPCompleter.greedy=True

In [2]:
import pandas as pd
import scipy as sp
from scipy import stats
import numpy as np

COVIDDataSet = pd.read_csv("c:\michael_docs\git repositories\covid-tracking-data/data/states_daily_4pm_et.csv")
COVIDDataSet

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200526,AK,411.0,44553.0,NaN,12.0,NaN,NaN,NaN,NaN,...,NaN,44964,44964,44964,2,0.0,0.0,490.0,2.0,492.0
1,20200526,AL,15396.0,178363.0,NaN,NaN,1671.0,NaN,551.0,NaN,...,1671.0,193759,193759,193759,1,13.0,42.0,2778.0,666.0,3444.0
2,20200526,AR,6180.0,105593.0,NaN,107.0,617.0,NaN,NaN,18.0,...,617.0,111773,111773,111773,5,2.0,12.0,0.0,151.0,151.0
3,20200526,AS,0.0,124.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,124,124,124,60,0.0,0.0,0.0,0.0,0.0
4,20200526,AZ,16783.0,173948.0,NaN,818.0,1988.0,336.0,NaN,208.0,...,1988.0,190731,190731,190731,4,1.0,27.0,2727.0,222.0,2949.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4604,20200126,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4605,20200125,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4606,20200124,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4607,20200123,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4608,20200122,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,NaN,NaN,NaN,NaN,NaN

In [3]:
NCDataFrame = COVIDDataSet[COVIDDataSet.state == 'NC']
NCDataFrame = NCDataFrame[NCDataFrame.date >= 20200401]
NCDataFrame = NCDataFrame[["date", "state", "positiveIncrease", "totalTestResultsIncrease"]]

In [6]:
linRegress  = stats.linregress(NCDataFrame["positiveIncrease"], NCDataFrame["totalTestResultsIncrease"])

In [7]:
linRegress.rvalue

0.7400415751406587