In [1]:
%config IPCompleter.greedy=True

In [2]:
import pandas as pd
import scipy as sp
from scipy import stats
import numpy as np

COVIDDataSet = pd.read_csv("c:\michael_docs\git repositories\covid-tracking-data/data/states_daily_4pm_et.csv")
COVIDDataSet

,date,state,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,hospitalized,total,totalTestResults,posNeg,fips,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease
0,20200524,AK,408.0,43099.0,NaN,10.0,NaN,NaN,NaN,NaN,...,NaN,43507,43507,43507,2,0.0,0.0,1156.0,0.0,1156.0
1,20200524,AL,14327.0,171472.0,NaN,NaN,1612.0,NaN,537.0,NaN,...,1612.0,185799,185799,185799,1,5.0,23.0,2734.0,389.0,3123.0
2,20200524,AR,5922.0,102659.0,NaN,86.0,598.0,NaN,NaN,17.0,...,598.0,108581,108581,108581,5,3.0,8.0,5224.0,310.0,5534.0
3,20200524,AS,0.0,124.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,124,124,124,60,0.0,0.0,0.0,0.0,0.0
4,20200524,AZ,16339.0,167302.0,NaN,804.0,1945.0,322.0,NaN,201.0,...,1945.0,183641,183641,183641,4,1.0,15.0,2902.0,300.0,3202.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4492,20200126,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4493,20200125,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4494,20200124,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4495,20200123,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,0.0,0.0,0.0,0.0,0.0
4496,20200122,WA,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,1,1,1,53,NaN,NaN,NaN,NaN,NaN

In [5]:
NCDataFrame = COVIDDataSet[COVIDDataSet.state == 'NC']
NCDataFrame = NCDataFrame[NCDataFrame.date >= 20200401]
NCDataFrame = NCDataFrame[["date", "state", "positiveIncrease", "totalTestResultsIncrease"]]

In [6]:
stats.linregress(NCDataFrame["positiveIncrease"], NCDataFrame["totalTestResultsIncrease"])

LinregressResult(slope=17.083994160037857, intercept=-1066.3460950493036, rvalue=0.7643219853201889, pvalue=1.7552546167116775e-11, stderr=1.9987563153088013)